query TwoRandomPeople {
  p1: randomPerson(id: 1) {
    id
    name
    mass
  }
  p2: randomPerson(id: 2) {
    id
    name
    mass
  }
}

query TwoRandomStarships {
  p1: randomStarship(id: 1) {
    id
    name
    crew {
      id
    }
  }
  p2: randomStarship(id: 2) {
    id
    name
    crew {
      id
    }
  }
}